name: Hello with Variables

on:
  push:
    branches: [ main ]

jobs:
  greet:
    runs-on: ubuntu-latest

    env:
      NAME: Sagar
      EMOJI: "🔥"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use variables
      run: echo "Hello, $NAME $EMOJI! Welcome to GitHub Actions"
