name: Matrix Example

on:
  push:
    branches: [ main ]

jobs:
  greet-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name: [Alice, Bob, Charlie]
        emoji: ["🎉", "🚀", "🔥"]

    steps:
    - name: Say hi to ${{ matrix.name }}
      run: echo "Hello, ${{ matrix.name }}! ${{ matrix.emoji }}"
